spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://61.14.208.8:3307/lxp
    username: lxp
    password: gocle123!@#

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gocle.lxp.domain

elasticsearch:
  host: localhost
  port: 9200
  scheme: http
  index:
    learning-log: learning_log

jwt:
  secret: GOCL_LXP_SUPER_SECRET_KEY_12345678901234567890